# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Page:
  fields:
    default: title, body
    list: title, body, test
    form: title, body
  order_by: 
  relationships: 
  filters: created_at
  search: title
  application: typus_test

